version: "3.7"

services:
  webserver:
    container_name: "webserver"
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
